# Generated by Django 6.0.7 on 2026-08-11 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Document Title')),
                ('description', models.TextField(verbose_name='Document Description')),
                ('file', models.FileField(help_text='Allowed file types: PDF, DOC, DOCX, PPT, PPTX, TXT', upload_to='documents/%Y/%m/%d/', verbose_name='File')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='File Size (KB)')),
                ('document_type', models.CharField(choices=[('NOTES', 'Study Notes'), ('PAST_PAPER', 'Past Paper'), ('ASSIGNMENT', 'Assignment'), ('BOOK', 'Book'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Document Type')),
                ('course_code', models.CharField(blank=True, max_length=20, verbose_name='Course Code')),
                ('course_name', models.CharField(blank=True, max_length=100, verbose_name='Course Name')),
                ('tags', models.CharField(blank=True, help_text='Separate with commas, e.g.: programming, python, database', max_length=255, verbose_name='Keywords')),
                ('download_count', models.IntegerField(default=0, verbose_name='Download Count')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approved')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
